name: Backend Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests (if any)
      run: |
        cd backend
        # Add test commands here when tests are available
        echo "Tests would run here"

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        cd backend
        # Build Docker image
        docker build -f Dockerfile -t mcu-copilot-backend:latest .
        docker tag mcu-copilot-backend:latest mcu-copilot-backend:${{ github.sha }}

    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Navigate to project directory
          cd /root/mcu-copilot

          # Pull latest code
          git pull origin main

          # Update backend service
          cd backend
          docker-compose down
          docker-compose build
          docker-compose up -d

          # Wait for service to start
          sleep 10

          # Health check
          curl -f http://localhost:8000/health || exit 1

          echo "Backend deployment completed successfully!"